events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=10s;

    server {
        listen 80;

        location ^~ /api/auth/ {
            set $service "auth-service:8000";
            rewrite ^/api/auth/(.*) /$1 break;
            proxy_pass http://$service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location ^~ /api/spaces/ {
            set $service "space-service:8000";
            rewrite ^/api/spaces/(.*) /$1 break;
            proxy_pass http://$service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location ^~ /api/reservations/ {
            set $service "reservation-service:8000";
            rewrite ^/api/reservations/(.*) /$1 break;
            proxy_pass http://$service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location ^~ /api/billing/ {
            set $service "billing-service:8000";
            rewrite ^/api/billing/(.*) /$1 break;
            proxy_pass http://$service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
